### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chaoming** [varstr/uaparser#3]
When the user agent is "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36", I got this error when try to get Device.Name.

Browser.Name and OS.Name both work well.

What is the return when the Parser can't find the match? nil?

**Comment by varstr** [comment]
Yes, all these info items `Browser/Device/DeviceType/OS` could be nil if parser failed to find a proper match.
